name: Maintance
version: '${version}'
main: org.dasultra.main.Main
api-version: '1.20'
authors: [DasUltra]
description: Maintance Sytem for Spigot
website: https://team-ultra.eu

commands:
    maintance:
        description: Maintance Command
        aliases: [m]